# Generated by Django 6.0 on 2025-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'verbose_name': 'HOD', 'verbose_name_plural': 'HODs'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name': 'Researcher', 'verbose_name_plural': 'Researchers'},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'verbose_name': 'Reviewer', 'verbose_name_plural': 'Reviewers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
