# Generated by Django 6.0 on 2026-01-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_hod_options_alter_researcher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='total_department_budget',
            field=models.DecimalField(decimal_places=2, default=500000.0, help_text='Total funds available for the department', max_digits=15),
        ),
    ]
