# Generated by Django 6.0 on 2026-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='deptID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='researchinterests',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
