# Generated by Django 6.0 on 2025-12-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('grantID', models.AutoField(primary_key=True, serialize=False)),
                ('totalAllocatedAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetID', models.AutoField(primary_key=True, serialize=False)),
                ('totalSpent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remainingBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grants.grant')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposalID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('version', models.FloatField(default=1.0)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('milestonesAchieved', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grants.proposal'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('feedbackComments', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reviewer')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.proposal')),
            ],
        ),
    ]
