# Generated by Django 6.0 on 2025-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expendituresDetails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
