# Generated by Django 6.0 on 2025-12-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_alter_evaluation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/pdfs/'),
        ),
    ]
