# Generated by Django 6.0 on 2026-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_proposal_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
