# Generated by Django 6.0 on 2026-01-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_proposal_requested_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='remainingBalance',
        ),
    ]
