# Generated by Django 6.0 on 2026-02-05 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_remove_budget_remainingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='expenditure_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount spent during this reporting period', max_digits=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload only PDF or Word documents (.doc, .docx)', null=True, upload_to='proposals/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
